apiVersion: v1
kind: Namespace
metadata:
  name: test-remediation
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: remediation-group
  namespace: test-remediation
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 name: node-healthcheck-operator-subscription
 namespace: test-remediation
spec:
  channel: stable
  name: node-healthcheck-operator
  source: nhc-upstream
  sourceNamespace: openshift-marketplace

 